2.Templates/4. DTL overview/project/my_app/urls.py
from django.urls import path
from . import views

app_name="my_app"

urlpatterns=[
    path('',views.index,name="index"),
    path('first',views.first,name="first"),
    path('second',views.second,name="second"),
    path('inherited',views.inherited,name="inherited"),
]

2.Templates/4. DTL overview/project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("my_app.urls"))
]

2.Templates/4. DTL overview/project/my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return HttpResponse("Hello this is the index page. go to /first and /second for the page view")
def first(request):
    return render(request,"my_app/first.html")

def second(request):
    return render(request,"my_app/second.html")

def inherited(request):
    return render(request,"my_app/inherited.html")

2.Templates/4. DTL overview/project/my_app/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Base {% endblock title %}</title>
</head>
<body>
    {% block body %}
        
Base content

    {% endblock body %}
</body>
</html>

2.Templates/4. DTL overview/project/my_app/templates/my_app/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First</title>
</head>
<body>
    <h1>This is the first page content</h1>
    <br>
    If you want to go to second, click here <a href="{% url 'my_app:second' %}">Second</a>
</body>
</html>

2.Templates/4. DTL overview/project/my_app/templates/my_app/inherited.html
{% extends 'my_app/base.html' %}

{% block  title %}Inherited Page{% endblock %}

{% block body %}
    Inherited Content
{% endblock %}

<!-- IN JINJA FLASK, we use endblock the block name, but here only endblock -->

2.Templates/4. DTL overview/project/my_app/templates/my_app/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Second</title>
</head>
<body>
    <h1>This is the second page content</h1>
    <br>
    <ol>
        {% for i in "Hello World"  %}
            <li>{{i}}</li>
        {% endfor %}
    </ol>

    {% if 1 == 2 %}
        {{True}}
    {% else %}
        {{False}}
    {% endif %}
</body>
</html>